#pragma once

#define MAX_PARTICLE_COUNT 3000
#define START_PARTICLE_COUNT 6
#define CIRCLE_RADIUS 50

#define RENDER_PARTICLE_RADIUS 3

#define INTERACTION_RADIUS 20.0f
#define MAX_EDGE_LENGTH 5.0f
#define NOISE_FORCE 0.1f
#define ATTRACTION_FORCE 0.05f
#define REPULSION_FORCE 1.0f
#define FRICTION 0.9f
#define MAX_SPEED 2.0f
